FROM mcr.microsoft.com/devcontainers/python:1-3.12

# SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Uninstall pre-installed formatting and linting tools
# They would conflict with our pinned versions
# RUN \
#     pipx uninstall pydocstyle \
#     && pipx uninstall pycodestyle \
#     && pipx uninstall mypy \
#     && pipx uninstall pylint

RUN \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        # Additional library needed by some tests and accordingly by VScode Tests Discovery
        bluez \
        ffmpeg \
        libudev-dev \
        libavformat-dev \
        libavcodec-dev \
        libavdevice-dev \
        libavutil-dev \
        libgammu-dev \
        libswscale-dev \
        libswresample-dev \
        libavfilter-dev \
        libpcap-dev \
        libturbojpeg0 \
        libyaml-dev \
        libxml2 \
        git \
        cmake \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Add go2rtc binary
COPY --from=ghcr.io/alexxit/go2rtc:latest /usr/local/bin/go2rtc /bin/go2rtc

# Install uv
# RUN pip3 install uv

WORKDIR /usr/src

# Setup hass-release
# RUN git clone --depth 1 https://github.com/home-assistant/hass-release \
    # && uv pip install --system -e hass-release/ \
    # && chown -R vscode /usr/src/hass-release/data

USER vscode
# ENV VIRTUAL_ENV="/home/vscode/.local/ha-venv"
# RUN uv venv $VIRTUAL_ENV
# ENV PATH="$VIRTUAL_ENV/bin:$PATH"

WORKDIR /tmp

RUN python3 -m pip install --upgrade --disable-pip-version-check "pip<23.2,>=21.3.1"
RUN python3 -m pip install --upgrade --disable-pip-version-check "setuptools" "wheel"

COPY requirements*.txt ./
RUN python3 -m pip install --upgrade --disable-pip-version-check --requirement "requirements_lint.txt"
RUN python3 -m pip install --upgrade --disable-pip-version-check --requirement "requirements_core_min.txt"
RUN python3 -m pip install --upgrade --disable-pip-version-check --requirement "requirements_test.txt"

# Set the default shell to bash instead of sh
ENV SHELL /bin/bash